schema_version = 7

[app_settings]
launch_at_login = true
check_for_updates = false
update_prompt_seen = true
show_in_menu_bar = false
auto_install_updates = false
capture_mouse_events = true
app_icon = "openlogi"
auto_download_assets = true
asset_source = "automatic"
thumbwheel_sensitivity = 14
appearance = "system"
smooth_scroll = false
vertical_scroll_sensitivity = 14
ui_scale = "normal"
device_view_mode = "grid"
mouse_profile_target = "pointer"

[devices.0b034.bindings]
Thumbwheel = "NextTab"

[devices."serial:2405lz512ed8".identity]
display_name = "MX Master 3S"
codename = "MX Master 3S"
kind = "mouse"

[devices."serial:2405lz512ed8".identity.model_info]
entity_count = 3
unit_id = [
    0,
    0,
    0,
    0,
]
model_ids = [
    45108,
    0,
    0,
]
extended_model_id = 0

[devices."serial:2405lz512ed8".identity.model_info.transports]
usb = false
equad = false
btle = true
bluetooth = false

[devices."serial:2405lz512ed8".identity.capabilities]
buttons = true
pointer = true
lighting = false
scroll_inversion = true
hires_wheel = true
thumbwheel = true
haptic_feedback = false
haptic_panel = false
dpi_gestures = true

[devices."serial:2405lz512ed8".links."direct:046d:b034".capabilities]
buttons = true
pointer = true
lighting = false
scroll_inversion = true
hires_wheel = true
thumbwheel = true
haptic_feedback = false
haptic_panel = false
dpi_gestures = true

[devices."serial:2405lz512ed8".bindings]
ThumbwheelScrollUp = "PrevTab"
ThumbwheelScrollDown = "NextTab"

[keyboard]
